src/range.coffee

Takes care of issues #11 and #12

add valid type and average component

---

spec/range-spec.coffee
src/range.coffee

* Added support for common characters ($ and ,) in ranges (issue #16)
* Added support for decimals in ranges. Test for ranges with no delimiter. 
* Limited range avg to two decimal places

More robust parsing

---

package.json
spec/city-spec.coffee
spec/faker-spec.coffee
spec/first-name-spec.coffee
spec/index-spec.coffee
spec/last-name-spec.coffee
spec/state-spec.coffee
spec/url-spec.coffee
src/boolean.coffee
src/city.coffee
src/credential.coffee
src/date.coffee
src/email.coffee
src/faker.coffee
src/first-name.coffee
src/index.coffee
src/last-name.coffee
src/number.coffee
src/phone.coffee
src/postal-code.coffee
src/range.coffee
src/ssn.coffee
src/state.coffee
src/time.coffee
src/url.coffee

Added additional types in order to furnish examples for those data points.

Added examples to types.

---

spec/gender-spec.coffee
src/gender.coffee
src/index.coffee

Added gender type

---

spec/examples-spec.coffee
spec/index-spec.coffee
src/credential.coffee
src/date.coffee
src/email.coffee
src/gender.coffee
src/index.coffee
src/normalize.coffee
src/number.coffee
src/phone.coffee
src/postal-code.coffee
src/range.coffee
src/ssn.coffee
src/state.coffee
src/time.coffee
src/url.coffee

This treatment is consistent with the way examples are parsed and normalized for fields.
@cgrayson, would you mind?

Parse and normalize examples

---

spec/gender-spec.coffee
src/gender.coffee

Add abbr to gender

---

spec/string-spec.coffee
src/boolean.coffee
src/string.coffee

String type casts all other types as a string primitive

---

spec/phone-spec.coffee
src/phone.coffee

Include extension in normalized phone number

---

spec/range-spec.coffee
src/range.coffee

The `mid` component is the average of the max and min, rounded down to the nearest whole number.

Support the 'mid' component for the Range type

---

spec/phone-spec.coffee
src/phone.coffee

add is_tollfree attribute to phone type 

---

src/state.coffee

add full name for DC

---

src/types/url.coffee

Add format validity operators to url type operators

---

package.json
src/types/phone.coffee

This seemed to resolve the issue with closure not being found.

Use a more recent version of libphonenumber

---

.npmrc
CHANGELOG.md
package.json
spec/email-spec.coffee
src/types/email.coffee

Refactor email parsing

---

CHANGELOG.md
package.json

fixes #105 
Nothing appears to have broken...
Is there anything else I can do to ensure nothing has broken?

Update handlebars to 4.0.0

---

.travis.yml
CHANGELOG.md
package-lock.json
package.json
src/types/number.coffee
src/types/phone.coffee

Previous changes for 4.17.1 were never cut-released.

add 'is between' operator to number type

---

.github/workflows/release.yml
.github/workflows/test.yml

> Description here
> Link to Clubhouse Ticket Goes Here

add release action

---

package-lock.json
package.json

> Description here
> Link to Clubhouse Ticket Goes Here

Change git protocol for chrono-node

---

package-lock.json
package.json

Forgot to do this in the last PR
[shortcut #37783](https://app.shortcut.com/active-prospect/story/37783/trustedform-cert-url-type)

Update trustedform-cert-id library

---

lib/types/dob.js
package.json
test/dob.test.js

> parse and normalize dob examples
> https://app.shortcut.com/active-prospect/story/46668/fix-dob-type-examples

sc-46668/fix-dob-type-examples

---

lib/ensureString.js
lib/types/email.js
lib/types/phone.js
lib/types/postal_code.js
lib/types/ssn.js
lib/types/state.js
lib/types/street.js
lib/types/time.js
lib/types/url.js
test/boolean.test.js
test/date.test.js
test/dob.test.js
test/email.test.js
test/gender.test.js
test/phone.test.js
test/postal-code.test.js
test/ssn.test.js
test/state.test.js
test/street.test.js
test/time.test.js
test/url.test.js

Adds protection against fatal errors when parsing JavaScript objects (vs. strings).
https://app.shortcut.com/active-prospect/story/39505/error-converting-object-to-primitive-value-crashes-handler

Sc 39505/error converting object to primitive value

---

.github/workflows/test.yml
lib/types/url.js
test/url.test.js

update for node 18: use WHATWG URL parsing
https://app.shortcut.com/active-prospect/story/47910/fix-dependency-errors-in-node-18

update for node 18: use WHATWG URL parsing

---

lib/aggregations/phone.js
test/aggregate.test.js

didn't realize I should've updated this in my previous pr because it wasn't covered in the tests
https://app.shortcut.com/active-prospect/story/75305/fix-phone-1-country-code-to-provide-the-correct-country-code-instead-of-us

update phone aggregations
