spec/operators-spec.coffee
src/boolean.coffee
src/credential.coffee
src/date.coffee
src/email.coffee
src/number.coffee
src/phone.coffee
src/postal-code.coffee
src/range.coffee
src/ssn.coffee
src/time.coffee

This will be used to implement a `/types` API which will indicate which operators can be used with each type.
@cgrayson and @justinwinslow, mind having a look at this?

Add operators property to each type

---

spec/range-spec.coffee
src/range.coffee

Fixing a few bugs for range parsing:
- Allow parsing of objects that don't have a `replace` property. Especially useful when parsing number types
- Ensure that the `avg` property is a number type

Improve range parsing

---

spec/postal-code-spec.coffee
src/postal-code.coffee

A recent bson serialization change
(https://jira.mongodb.org/browse/NODE-517) omits object properties that
have an undefined value. This change ensures that undefined postal code
values are saved as null, so that they persist.

Ensure dynamic postal code properties are saved as null

---

spec/index-spec.coffee
src/index.coffee

This is useful for any project that uses leadconduit-types where there is an object with a leadconduit-type within it that needs to be cloned.

Adding clone function

---

spec/date-spec.coffee
spec/time-spec.coffee

@alexkwolfe re: [this comment](https://github.com/activeprospect/leadconduit-integration-leadid/pull/1#discussion_r44064764), is this the test coverage you were suggesting?

add tests for 'date' and 'time' to ensure they can parse a Date object

---

CHANGELOG.md
src/string.coffee

Fixes #44. 
I don't think this will affect lead handling, if flows have rules
in place testing 'string' values with these operators. It will
cause validation warnings on those flows the next time they're
saved.

Remove 'string' operators 'includes' & 'does not include'

---

CHANGELOG.md
spec/index-spec.coffee
src/index.coffee

this came up after a deploy today, an integration of 360's that
appends 'array'-type data started stringifying the array
('[object Object],[object Object],...'). Turned out to be caused
by the variable 'type' now being declared on line 9 of
index.coffee, which kept its last value and caused the conditional
'type?' on line 19 to incorrectly be true.
(line numbers reference [previous version of index.coffee](https://github.com/activeprospect/leadconduit-types/blob/d4d1cb6eee9fdc0d25145242269df904364a4843/src/index.coffee))

fix problem of parsing non-type types (e.g., array)

---

spec/aggregate-spec.coffee
src/aggregate.coffee
src/aggregations/boolean.coffee
src/aggregations/number.coffee
src/aggregations/range.coffee
src/aggregations/state.coffee

This simplifies aggregation of more typed fields. In cases where the field value is invalid, then nothing will be aggregated. In cases where the field is valid, then aggregate the simplest possible value. Normally that means aggregating the primitive value. The exception is range, where we aggregate the components of the value (`min`, `max`, `mid`, `avg`).

Add aggregations for boolean, number, range, and state

---

spec/aggregate-spec.coffee
src/aggregations/date.coffee
src/aggregations/time.coffee

I missed adding logic for time and date aggregations. This PR takes care of that.

Aggregate time and date types as strings

---

CHANGELOG.md
package.json
spec/date-spec.coffee
src/types/date.coffee

AP support reported [an issue in Slack today](https://activeprospect.slack.com/archives/support/p1489583948461145), where a `dob` value of `14%2F03%2F1985` was being parsed as "March 19, 2014" (vs. "March 14, 1985").
When I investigated I found two problems: the encoded `/`s were confusing the `moment.js` parser, and there was no pattern to parse "DD/MM/YYYY". This PR includes fixes and additional test coverage.

fix date parsing: unescape value; & parse dd/mm/yyyy when possible

---

spec/date-spec.coffee
src/types/date.coffee

After analyzing data from 3/16-3/20, these slight changes to allowed formats addressed nearly all the strict-parsing failures. 
I say "nearly all" because there were some that included a trailing timestamp which still failed parsing, but I found that those were all Ralis/Cashcall inbound, so I added code there ([PR 46](https://github.com/activeprospect/leadconduit-integration-cashcall/pull/46)) to ensure those were still parsed correctly.

add two date formats and change one, on the way to strict parsing

---

src/types/phone.coffee

add toll-free area codes to description

---

package-lock.json
package.json

`-rules` is only used in the test suite. Moving this dep into `devDependencies` allows public packages to use the `-types` module without having an NPM token

Move rules to devDependencies

---

lib/types/trustedform_url.js
test/trustedform-url.test.js

TrustedForm URL type now supports URLs using staging host names.
[Shortcut #37183](https://app.shortcut.com/active-prospect/story/37183/allow-a-trustedform-ping-url-to-be-passed-in-the-trustedfrom-cert-url-field-of-trustedform-data-service-integration)

TrustedForm URL now supports staging URLs

---

lib/types/trustedform_url.js
test/trustedform-url.test.js

This PR performs deeper checking of the host name portion of the TrustedForm URL. It now supports development certs and ensures that the env of the cert's host name matches the env of the running server process. This last check ensures that we don't try to decrypt a production cert with the staging private key.
[Shortcut #37783](https://app.shortcut.com/active-prospect/story/37783/trustedform-cert-url-type)

Support checking cert host name for dev environment and make sure cert env matches server env

---

lib/types/phone.js

Removes the code which sends DataDog messages about an inability to log unparsable phone numbers.
[Stop Spamming DataDog with Phone Number Errors](https://app.shortcut.com/active-prospect/story/38267/stop-spamming-datadog-with-phone-number-errors)

Stop logging to datadot unparsable phone numbers

---

lib/index.js
lib/types/dob.js
test/index.test.js
test/mask.test.js

<pre>
remove dob masking (index.js)
set dob.maskable to false (which triggers data-masking in lib/handler/middleware/source.js)
remove dob.parsed.masked (which triggers masking in requests via leadconduit-mask)
add function getHideableType(field)
needed because event data from db doesn't have explicit type info
returns "dob" if field has age & year attributes
return null otherwise
add function shouldHide(field)
returns boolean based on call to getHideableType() being null or not
add function hide(field)
calls getHideableType(field)
if result is not null, mask raw & normal based on type (e.g., "dob")
</pre>
> https://app.shortcut.com/active-prospect/story/50139/super-admin-can-export-leads-with-full-dob

Sc 50139/super admin can export leads with full dob

---

lib/index.js
lib/types/dob.js
test/index.test.js
test/mask.test.js

After conversations with Scott and Alex; we have decided to keep the dob type as a masked type, and make it optional to use a new standard field called dob secured or something to that effect.
> This reverts commit c121836ce2d77d05f4ba25d150c5940980a2f082.
> https://app.shortcut.com/active-prospect/story/50139/super-admin-can-export-leads-with-full-dob

Revert "Sc 50139/super admin can export leads with full dob (#157)"

---

package.json
test/time.test.js

Fixes the `time` type's handling of timestamps with more than 4 decimal places of fractional seconds.
This is accomplished by updating to use the latest public version of `chrono-node`, which is used for the fundamental time parsing. 
@alexkwolfe - Let me know if you have concerns about this change - it replaces your previously branched version at [`git+https://github.com/alexkwolfe/chrono.git#milliseconds`](https://github.com/alexkwolfe/chrono/commits/milliseconds). It looks like your change was to add support for parsing milliseconds (what I'm calling "fractional seconds" here). Now the mainline public version of `chrono-node` does that itself, plus whatever other fixes (including vulnerabilities) since your fork. All the time tests still pass, of course. …

update to use latest chrono-node/handle excessive fractional seconds

---

lib/types/ip.js
lib/types/url.js
test/ip.test.js
test/url.test.js

> Create IP type, Validate IP addresses using Node's built-in URL API, fix minor issues with url type for clarity.
> https://app.shortcut.com/active-prospect/story/60407/add-ipv6-support-to-the-ip-address-data-type

Sc 60407/add ipv6 support to the ip address data type

---

.github/workflows/test-common.yml
lib/types/email.js
test/email.test.js

> add try/catch for invalid domain; run lint:fix
> https://app.shortcut.com/active-prospect/story/64578/fix-invalid-url-bug

sc-64578/fix-invalid-url-bug

---

lib/types/city.js
lib/types/email.js
lib/types/first_name.js
lib/types/last_name.js
lib/types/state.js
lib/types/street.js
lib/types/string.js
lib/types/url.js
package.json
test/city.test.js
test/first-name.test.js
test/last-name.test.js

> add `is obscene` and `is not obscene` operators
> https://app.shortcut.com/active-prospect/story/74325/profanity-obscenity-package-implement-as-a-unary-rule-for-leads-filtering

sc-74325/profanity-obscenity-package-implement-as

---

lib/types/phone.js
package.json
test/examples.test.js
test/phone.test.js

- Updated phone number parsing to correctly set country code for non-North American numbers
- Now captures the numeric country calling code and exposes that as a new component of the phone type
- Removed some old, half-baked code that tried to handle Canadian and UK numbers but didn't actually work, including a test for UK numbers that was always skipped
- Removed the code which looked up and set the national dialing prefix for a number which was never actually exposed as a component of the phone type
https://app.shortcut.com/active-prospect/story/75305/fix-phone-1-country-code-to-provide-the-correct-country-code-instead-of-us

improve handling of non-US phone numbers
